services:
  pgvector:
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'